[package]
name = "loreweaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.3"
clap = { version = "4.3.24", features = ["derive"] }
lazy_static = "1.4.0"
tiktoken-rs = "0.5.1"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
google-cloud-storage = "0.13.1"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
redis = { version = "0.23.3", features = [
    "tokio-comp",
    "tokio-rustls-comp",
    "json",
] }
chrono = "0.4.31"
thiserror = "1.0.49"
async-trait = "0.1.73"
