[package]
name = "loreweaver-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.2"
serenity = { version = "0.11.6", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
clap = { version = "4.3.24", features = ["derive"] }
dotenv = "0.15.0"
lazy_static = "1.4.0"
num-traits = "0.2.16"
tiktoken-rs = "0.5.1"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
