[package]
name = "loreweaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.3"
serenity = { version = "0.11.6", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
clap = { version = "4.3.24", features = ["derive"] }
dotenv = "0.15.0"
lazy_static = "1.4.0"
num-traits = "0.2.16"
tiktoken-rs = "0.5.1"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
google-cloud-storage = "0.13.1"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
redis = { version = "0.23.3", features = [
    "tokio-comp",
    "tokio-rustls-comp",
    "json",
] }
chrono = "0.4.31"
