[package]
publish = true
name = "loom"
version = "1.0.0"
edition = "2021"
description = "Managing long conversations with ChatGPT"
readme = "README.md"
repository = "https://github.com/snowmead/loom"
license = "MIT"
keywords = ["chatbot", "gpt", "openai", "chatgpt"]
categories = ["api-bindings"]
exclude = [
    "compose.yaml",
    ".idea",
    ".github",
    ".DS_Store",
    ".gitignore",
    ".rustfmt.toml",
]

[dependencies]
async-openai = "0.15.0"
clap = { version = "4.3.24", features = ["derive"] }
lazy_static = "1.4.0"
tiktoken-rs = "0.5.1"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
google-cloud-storage = "0.14.0"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
redis = { version = "0.23.3", features = [
    "tokio-comp",
    "tokio-rustls-comp",
    "json",
] }
chrono = "0.4.31"
thiserror = "1.0.49"
async-trait = "0.1.73"
num-traits = "0.2.17"
bounded-integer = { version = "0.5.7", features = ["types", "num-traits02"] }
